"""Adapters from :mod:`plant_schema` to external physics engines.

The adapters keep the high-fidelity pieces that external engines do not natively
know about (stepper torque-speed envelope, command latency/jitter, and Stribeck
friction) explicit instead of silently discarding them.
"""

from __future__ import annotations

import html
import json
import math
from typing import Any

from .plant_schema import ActuatorPlantParameters


def clipped_motor_torque_nm(
    parameters: ActuatorPlantParameters,
    requested_torque_nm: float,
    motor_speed_rad_s: float,
    *,
    current_a: float | None = None,
) -> float:
    """Common runtime torque limiter for MuJoCo/Chrono control callbacks."""
    limit = parameters.torque_limit_nm(motor_speed_rad_s, current_a=current_a)
    return max(-limit, min(float(requested_torque_nm), limit))


def mujoco_joint_properties(parameters: ActuatorPlantParameters) -> dict[str, dict[str, float]]:
    """Return properties that should be applied to existing MuJoCo joints.

    ``motor.armature`` should only be used when rotor inertia is not already
    represented by geometry.  Likewise, ``output.armature`` is an optional
    convenience for an output inertia that is not already in the wheel/body
    inertial properties.
    """
    return {
        "motor": {
            "armature": parameters.motor_inertia_kg_m2,
        },
        "output": {
            "armature": parameters.output_inertia_kg_m2,
            "damping": parameters.viscous_friction_nm_s_per_rad,
            "frictionloss": parameters.coulomb_friction_nm,
        },
    }


def mujoco_xml_fragment(
    parameters: ActuatorPlantParameters,
    *,
    motor_joint: str = "motor_rotor_joint",
    output_joint: str = "wheel_joint",
    tendon_name: str = "belt_compliance",
    actuator_name: str = "stepper_motor",
) -> str:
    """Generate an MJCF fragment for the elastic reduction and motor actuator.

    The fixed tendon coordinates are ``q_motor/N - q_output``.  This gives the
    same relative deformation used by the standalone two-inertia simulator.
    MuJoCo's native dry/viscous joint friction can cover the fitted Coulomb and
    viscous terms, while Stribeck friction and speed-dependent stepper torque
    should be applied from a control/passive-force callback.
    """
    parameters.validate()
    ratio = parameters.gear_ratio_motor_per_output
    stall_torque = parameters.torque_limit_nm(0.0)
    motor_joint = html.escape(motor_joint, quote=True)
    output_joint = html.escape(output_joint, quote=True)
    tendon_name = html.escape(tendon_name, quote=True)
    actuator_name = html.escape(actuator_name, quote=True)
    return f"""<!-- Generated by actuator_tool.plant_adapters -->
<!-- Apply these to the existing joints when not already represented by body inertia:
     motor joint: armature={parameters.motor_inertia_kg_m2:.12g}
     output joint: armature={parameters.output_inertia_kg_m2:.12g}
                   damping={parameters.viscous_friction_nm_s_per_rad:.12g}
                   frictionloss={parameters.coulomb_friction_nm:.12g}
-->
<tendon>
  <fixed name="{tendon_name}"
         stiffness="{parameters.belt_stiffness_nm_per_rad:.12g}"
         damping="{parameters.belt_damping_nm_s_per_rad:.12g}"
         springlength="0">
    <joint joint="{motor_joint}" coef="{1.0 / ratio:.12g}"/>
    <joint joint="{output_joint}" coef="-1"/>
  </fixed>
</tendon>
<actuator>
  <!-- Runtime code should further clip ctrl by the measured torque-speed map. -->
  <motor name="{actuator_name}" joint="{motor_joint}" gear="1"
         ctrllimited="true" ctrlrange="{-stall_torque:.12g} {stall_torque:.12g}"/>
</actuator>"""


def mujoco_runtime_config(parameters: ActuatorPlantParameters) -> dict[str, Any]:
    """Return the non-MJCF behavior a controller wrapper should implement."""
    return {
        "gear_ratio_motor_per_output": parameters.gear_ratio_motor_per_output,
        "torque_speed_map": [
            {"speed_rad_s": point.speed_rad_s, "torque_nm": point.torque_nm}
            for point in parameters.motor_torque_speed_map
        ],
        "command_latency_s": parameters.command_latency_s,
        "command_jitter_std_s": parameters.command_jitter_std_s,
        "stribeck": {
            "coulomb_friction_nm": parameters.coulomb_friction_nm,
            "static_friction_nm": parameters.static_friction_nm,
            "viscous_friction_nm_s_per_rad": parameters.viscous_friction_nm_s_per_rad,
            "stribeck_velocity_rad_s": parameters.stribeck_velocity_rad_s,
            "smoothing_velocity_rad_s": parameters.friction_smoothing_velocity_rad_s,
        },
        "motor_encoder": parameters.motor_encoder.__dict__.copy(),
        "output_encoder": parameters.output_encoder.__dict__.copy(),
    }


def chrono_parameter_dict(parameters: ActuatorPlantParameters) -> dict[str, Any]:
    """Return a small engine-neutral payload for a PyChrono integration."""
    parameters.validate()
    return {
        "motor_shaft_inertia_kg_m2": parameters.motor_inertia_kg_m2,
        "output_shaft_inertia_kg_m2": parameters.output_inertia_kg_m2,
        # Chrono ChShaftsGear defines w2 = ratio * w1.
        "chrono_transmission_ratio": 1.0 / parameters.gear_ratio_motor_per_output,
        "torsional_stiffness_nm_per_rad": parameters.belt_stiffness_nm_per_rad,
        "torsional_damping_nm_s_per_rad": parameters.belt_damping_nm_s_per_rad,
        "torque_speed_map": [
            (point.speed_rad_s, point.torque_nm) for point in parameters.motor_torque_speed_map
        ],
        "output_friction": {
            "coulomb_nm": parameters.coulomb_friction_nm,
            "static_nm": parameters.static_friction_nm,
            "viscous_nm_s_per_rad": parameters.viscous_friction_nm_s_per_rad,
            "stribeck_velocity_rad_s": parameters.stribeck_velocity_rad_s,
            "smoothing_velocity_rad_s": parameters.friction_smoothing_velocity_rad_s,
        },
        "command_latency_s": parameters.command_latency_s,
        "command_jitter_std_s": parameters.command_jitter_std_s,
    }


def chrono_python_snippet(parameters: ActuatorPlantParameters) -> str:
    """Generate a PyChrono 10-style 1-D driveline setup.

    Project Chrono's ``ChShaftsGear`` supports transmission ratio plus compliant
    torsional stiffness/damping.  The generated snippet uses ``SetAppliedLoad``
    for motor and output loads so speed-dependent motor torque and fitted
    Stribeck friction can be updated at every simulation step.
    """
    parameters.validate()
    torque_map = [(point.speed_rad_s, point.torque_nm) for point in parameters.motor_torque_speed_map]
    return f'''# Generated by actuator_tool.plant_adapters
import math
import pychrono as chrono

system = chrono.ChSystemNSC()

motor_shaft = chrono.ChShaft()
motor_shaft.SetInertia({parameters.motor_inertia_kg_m2!r})
system.Add(motor_shaft)

output_shaft = chrono.ChShaft()
output_shaft.SetInertia({parameters.output_inertia_kg_m2!r})
system.Add(output_shaft)

belt = chrono.ChShaftsGear()
belt.Initialize(motor_shaft, output_shaft)
belt.SetTransmissionRatio({(1.0 / parameters.gear_ratio_motor_per_output)!r})  # w_out / w_motor
belt.SetCompliant(True, {parameters.belt_stiffness_nm_per_rad!r}, {parameters.belt_damping_nm_s_per_rad!r})
system.Add(belt)

TORQUE_SPEED_MAP = {torque_map!r}


def torque_limit(speed_rad_s):
    speed = abs(float(speed_rad_s))
    if speed <= TORQUE_SPEED_MAP[0][0]:
        return TORQUE_SPEED_MAP[0][1]
    for (s0, t0), (s1, t1) in zip(TORQUE_SPEED_MAP, TORQUE_SPEED_MAP[1:]):
        if speed <= s1:
            u = (speed - s0) / (s1 - s0)
            return t0 + u * (t1 - t0)
    return TORQUE_SPEED_MAP[-1][1]


def output_friction(speed_rad_s):
    v = float(speed_rad_s)
    smooth_sign = math.tanh(v / {parameters.friction_smoothing_velocity_rad_s!r})
    stribeck = {parameters.coulomb_friction_nm!r} + (
        {parameters.static_friction_nm!r} - {parameters.coulomb_friction_nm!r}
    ) * math.exp(-((abs(v) / {parameters.stribeck_velocity_rad_s!r}) ** 2))
    return smooth_sign * stribeck + {parameters.viscous_friction_nm_s_per_rad!r} * v


def apply_actuator_loads(requested_motor_torque_nm, external_output_load_nm=0.0):
    limit = torque_limit(motor_shaft.GetPosDt())
    motor_torque = max(-limit, min(float(requested_motor_torque_nm), limit))
    motor_shaft.SetAppliedLoad(motor_torque)
    output_shaft.SetAppliedLoad(-output_friction(output_shaft.GetPosDt()) - external_output_load_nm)

# Command latency/jitter ({parameters.command_latency_s!r} s mean,
# {parameters.command_jitter_std_s!r} s std) should be implemented in the
# controller/cosimulation command queue before calling apply_actuator_loads().
'''


def export_adapter_bundle(parameters: ActuatorPlantParameters) -> str:
    """Serialize the shared engine-adapter payload as JSON for build pipelines."""
    bundle = {
        "plant": parameters.as_dict(),
        "mujoco": {
            "joint_properties": mujoco_joint_properties(parameters),
            "runtime": mujoco_runtime_config(parameters),
        },
        "chrono": chrono_parameter_dict(parameters),
    }
    return json.dumps(bundle, indent=2)
